// generated by @ng-toolkit/universal
const port = process.env.PORT || 4000;
var compression = require('compression');


const server = require('./dist/server');
server.app.use(compression());
server.app.listen(port, () => {
    console.log(`Listening on: http://localhost:${port}`);
});

